export { ReactComponent as AddIcon } from './add.svg'
export { ReactComponent as BikeIcon } from './bike.svg'
export { ReactComponent as BusIcon } from './bus.svg'
export { ReactComponent as BusBikeIcon } from './bus-bike.svg'
export { ReactComponent as CarIcon } from './car.svg'
