version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.9

jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: /home/circleci/app
    steps:
      - checkout:
          path: /home/circleci/app
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Deploy application
          command: yarn deploy --stage production

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: includable-ecs
          filters:
            branches:
              only: master
